# Generated by Django 5.2.11 on 2026-03-26 08:50

import autoslug.fields
from slugify import slugify
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='business_name', slugify=slugify, unique=True),
        ),
    ]
